name: "Auto Update IP"
on:
  workflow_dispatch:
  schedule:
    - cron: "* */6 * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get IPS
        run: |
          curl -s https://raw.githubusercontent.com/yutian81/CFCDN-Auto/main/yx_ips.txt -o ${GITHUB_WORKSPACE}/yx_ips.txt
          curl -s https://raw.githubusercontent.com/yutian81/CFCDN-Auto/main/sgfd_ips.txt -o ${GITHUB_WORKSPACE}/sgfd_ips.txt 
          #curl -s https://raw.githubusercontent.com/yutian81/CFCDN-Auto/main/FDIP/all.txt -o ${GITHUB_WORKSPACE}/FDIP/all.txt
          #curl -s https://raw.githubusercontent.com/yutian81/CFCDN-Auto/main/CloudflareST/sg.csv -o ${GITHUB_WORKSPACE}/CloudflareST/sg.csv
          #curl -s https://raw.githubusercontent.com/yutian81/CFCDN-Auto/main/CloudflareST/sg.txt -o ${GITHUB_WORKSPACE}/CloudflareST/sg.txt
          #curl -s https://raw.githubusercontent.com/yutian81/CFCDN-Auto/main/CloudflareST/sgcs.txt -o ${GITHUB_WORKSPACE}/CloudflareST/sgcs.txt
          
      - name: Creat Message
        id: msg
        run: |
            echo "commit_message=Update $(date +"%Y-%m-%d %H:%M:%S")" >> "$GITHUB_OUTPUT"
 
      - name: Apply IP Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: ${{ steps.msg.outputs.commit_message }}
         branch: main
         commit_user_name: xj888xj
         commit_user_email: ${{ secrets.EMAIL }}
         commit_author: xj888xj <${{ secrets.EMAIL }}>

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 5
